from lib.experiment import Experiment
from lib.measurement import Measurement

print('10 students experiment')
exp = Experiment(100)
exp.generate_experiment(student_count = 10, join_chat_prob = 0.0)
exp.run_experiment()
measurement = Measurement(exp)
print(measurement.get_class_stats())
print(measurement.get_student_stats()[0])

print('50 students experiment')
exp = Experiment(100)
exp.generate_experiment(student_count = 50, join_chat_prob = 0.0)
exp.run_experiment()
measurement = Measurement(exp)
print(measurement.get_class_stats())
print(measurement.get_student_stats()[0])

print('100 students experiment')
exp = Experiment(100)
exp.generate_experiment(student_count = 100, join_chat_prob = 0.0)
exp.run_experiment()
measurement = Measurement(exp)
print(measurement.get_class_stats())
print(measurement.get_student_stats()[0])

print('10 students experiment')
exp = Experiment(100)
exp.generate_experiment(student_count = 10, join_chat_prob = 0.5)
exp.run_experiment()
measurement = Measurement(exp)
print(measurement.get_class_stats())
print(measurement.get_student_stats()[0])

print('50 students experiment')
exp = Experiment(100)
exp.generate_experiment(student_count = 50, join_chat_prob = 0.5)
exp.run_experiment()
measurement = Measurement(exp)
print(measurement.get_class_stats())
print(measurement.get_student_stats()[0])

print('100 students experiment')
exp = Experiment(100)
exp.generate_experiment(student_count = 100, join_chat_prob = 0.5)
exp.run_experiment()
measurement = Measurement(exp)
print(measurement.get_class_stats())
print(measurement.get_student_stats()[0])